<a href="https://colab.research.google.com/github/SewoongPark/SeSac_study_repo/blob/main/SVD%EA%B8%B0%EB%B0%98_%EC%B6%94%EC%B2%9C%EC%8B%9C%EC%8A%A4%ED%85%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

import warnings
import os

도서 평점 데이터 로드

In [11]:
rating_df = pd.read_csv('/content/drive/MyDrive/BX-CSV.zip (Unzipped Files)/BX-Book-Ratings.csv' , delimiter = ';' , encoding = 'latin_1', error_bad_lines = False)

<ipython-input-11-238946c30ebf>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  rating_df = pd.read_csv('/content/drive/MyDrive/BX-CSV.zip (Unzipped Files)/BX-Book-Ratings.csv' , delimiter = ';' , encoding = 'latin_1', error_bad_lines = False)

도서 정보 데이터 로드 & 특수 문자 처리를 위한 encoder 설정

In [3]:
book_df = pd.read_csv('/content/drive/MyDrive/BX-CSV.zip (Unzipped Files)/BX-Books.csv',
                      error_bad_lines = False,
                      delimiter = ';' ,
                      encoding = 'latin_1' )

<ipython-input-3-cfd31bc70eb2>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  book_df = pd.read_csv('/content/drive/MyDrive/BX-CSV.zip (Unzipped Files)/BX-Books.csv',
Skipping line 6452: expected 8 fields, saw 9
Skipping line 43667: expected 8 fields, saw 10
Skipping line 51751: expected 8 fields, saw 9

Skipping line 92038: expected 8 fields, saw 9
Skipping line 104319: expected 8 fields, saw 9
Skipping line 121768: expected 8 fields, saw 9

Skipping line 144058: expected 8 fields, saw 9
Skipping line 150789: expected 8 fields, saw 9
Skipping line 157128: expected 8 fields, saw 9
Skipping line 180189: expected 8 fields, saw 9
Skipping line 185738: expected 8 fields, saw 9

Skipping line 209388: expected 8 fields, saw 9
Skipping line 220626: expected 8 fields, saw 9
Skipping line 227933: expected 8 fields, saw 11
Skipping line 228957: expected 8 fields, saw 10
Skipping line 245933: expected 8 fields, saw 9
Skipping line 251296: expected 8 fields, saw 9
Skipping line 259941: expected 8 fields, saw 9
Skipping line 261529: expected 8 fields, saw 9

<ipython-input-3-cfd31bc70eb2>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book_df = pd.read_csv('/content/drive/MyDrive/BX-CSV.zip (Unzipped Files)/BX-Books.csv',

In [4]:
book_df

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [5]:
book_df.shape

(271360, 8)

사용자 정보 데이터 로드

In [7]:
user_df = pd.read_csv('/content/drive/MyDrive/BX-CSV.zip (Unzipped Files)/BX-Users.csv' , delimiter = ';' , error_bad_lines = False,encoding = 'latin_1' )

<ipython-input-7-30cc50862457>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  user_df = pd.read_csv('/content/drive/MyDrive/BX-CSV.zip (Unzipped Files)/BX-Users.csv' , delimiter = ';' , error_bad_lines = False,encoding = 'latin_1' )

In [8]:
user_df

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [ ]:
user_df.shape

(278858, 3)

In [ ]:
rating_df.shape

(1149780, 3)

In [12]:
data = pd.merge(rating_df, user_df, on = 'User-ID', how = 'inner') #공통된 요소들 기준으로 JOIN

In [13]:
data = pd.merge(data, book_df, on = 'ISBN', how = 'inner') #책 ID기준으로 JOIN

In [14]:
data

,User-ID,ISBN,Book-Rating,Location,Age,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,"tyler, texas, usa",NaN,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,"cincinnati, ohio, usa",23.0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,"strafford, missouri, usa",34.0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,"st. charles county, missouri, usa",2.0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,"beaverton, oregon, usa",NaN,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,"fort lee, new jersey, usa",NaN,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,"fort lee, new jersey, usa",NaN,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,"wakeman, ohio, usa",43.0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,"cedar park, texas, usa",NaN,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,"cedar park, texas, usa",NaN,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [15]:
data['ISBN'].nunique() # 도서 ID 종류 확인

270151

In [19]:
to_drop = [ 'Book-Author',	'Year-Of-Publication',	'Publisher']
data = data.drop(to_drop, axis=1, inplace=False)

KeyError: "['Book-Author', 'Year-Of-Publication', 'Publisher'] not found in axis"

In [20]:
data.shape

(1031136, 9)

In [21]:
data.rename(columns={'Book-Rating':'rating', 'User-ID':'user_id', 'Book-Title': 'title'}, inplace=True)

In [22]:
data.columns

Index(['user_id', 'ISBN', 'rating', 'Location', 'Age', 'title', 'Image-URL-S',
       'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [23]:
data2 = data.copy()

In [24]:
rating_df

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [25]:
user_df

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [26]:
book_df

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [27]:
data2['rating'] = data2['rating'].astype(float) # 연산을 위한 타입 변환

In [28]:
user_ids = data2['user_id'].unique().tolist()
#print(len(user_ids))
user2idx_dict = { u : i for i, u in enumerate(user_ids)}
#print(user2idx_dict)
idx2user_dict = {i : u for i, u in enumerate(user_ids)}
#print(idx2user_dict)

In [29]:
user_ids = data2['user_id'].unique().tolist() #user id 목록을 리스트에 담은 배열

user2idx_dict = {u : i for i, u in enumerate(user_ids)} #user_id에 index번호 메김
idx2user_dict = { i : u for i, u in enumerate(user_ids)} #u = user_id, i = index

book_ids = data2['ISBN'].unique().tolist() #isbn 목록을 리스트에 담은 배열

book2idx_dict = {b: i for i, b in enumerate(book_ids)} # b = index, i = isbn
idx2book_dict = {i: b for i, b in enumerate(book_ids)} # i = index, b = isbn

data2['user_idx'] = data2['user_id'].map(user2idx_dict)
'''
 data 데이터 프레임 내의 isbn이 dict의 b값과 일치하면 dict의 i값으로 변경,
 isbn -> index 한 값을 새로운 col에 추가
'''
data2['book_idx'] = data2['ISBN'].map(book2idx_dict)

num_users = data2['user_id'].nunique()
num_books = data2['ISBN'].nunique()
# 행렬분해를 위한 범위(가로, 세로)지정
print(num_users, num_books)

data2 = data2.sort_values(['user_idx', 'book_idx'])
data2 = data2.reset_index(drop = True)
data2

92106 270151

,user_id,ISBN,rating,Location,Age,title,Image-URL-S,Image-URL-M,Image-URL-L,user_idx,book_idx
0,276725,034545104X,0.0,"tyler, texas, usa",NaN,Flesh Tones: A Novel,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,0,0
1,2313,034545104X,5.0,"cincinnati, ohio, usa",23.0,Flesh Tones: A Novel,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,1,0
2,2313,0812533550,9.0,"cincinnati, ohio, usa",23.0,Ender's Game (Ender Wiggins Saga (Paperback)),http://images.amazon.com/images/P/0812533550.0...,http://images.amazon.com/images/P/0812533550.0...,http://images.amazon.com/images/P/0812533550.0...,1,273
3,2313,0679745580,8.0,"cincinnati, ohio, usa",23.0,In Cold Blood (Vintage International),http://images.amazon.com/images/P/0679745580.0...,http://images.amazon.com/images/P/0679745580.0...,http://images.amazon.com/images/P/0679745580.0...,1,326
4,2313,0060173289,9.0,"cincinnati, ohio, usa",23.0,Divine Secrets of the Ya-Ya Sisterhood : A Novel,http://images.amazon.com/images/P/0060173289.0...,http://images.amazon.com/images/P/0060173289.0...,http://images.amazon.com/images/P/0060173289.0...,1,1035
...,...,...,...,...,...,...,...,...,...,...,...
1031131,276442,2862749796,7.0,"genève, genève, switzerland",62.0,Le Huit,http://images.amazon.com/images/P/2862749796.0...,http://images.amazon.com/images/P/2862749796.0...,http://images.amazon.com/images/P/2862749796.0...,92102,270001
1031132,276618,3788097000,5.0,"stuttgart, \n/a\""., germany""",NaN,Ludwig Marum: Briefe aus dem Konzentrationslag...,http://images.amazon.com/images/P/3788097000.0...,http://images.amazon.com/images/P/3788097000.0...,http://images.amazon.com/images/P/3788097000.0...,92103,270082
1031133,276647,0553571001,0.0,"arlington heights, illinois, usa",13.0,Christmas With Anne and Other Holiday Stories:...,http://images.amazon.com/images/P/0553571001.0...,http://images.amazon.com/images/P/0553571001.0...,http://images.amazon.com/images/P/0553571001.0...,92104,270098
1031134,276647,0689822294,10.0,"arlington heights, illinois, usa",13.0,Heaven (Coretta Scott King Author Award Winner),http://images.amazon.com/images/P/0689822294.0...,http://images.amazon.com/images/P/0689822294.0...,http://images.amazon.com/images/P/0689822294.0...,92104,270099
1031135,276660,0583307841,8.0,"singapore, n/a, singapore",15.0,ROBOT RACE (MICRO ADV 6),http://images.amazon.com/images/P/0583307841.0...,http://images.amazon.com/images/P/0583307841.0...,http://images.amazon.com/images/P/0583307841.0...,92105,270103

In [30]:
data2['ISBN'].iloc[:len(data2)]

0          034545104X
1          034545104X
2          0812533550
3          0679745580
4          0060173289
              ...
1031131    2862749796
1031132    3788097000
1031133    0553571001
1031134    0689822294
1031135    0583307841
Name: ISBN, Length: 1031136, dtype: object

In [31]:
from scipy.sparse import coo_matrix, csr_matrix, csc_matrix, linalg
sparse_arr = coo_matrix((data2['rating'],
 (data2['user_idx'],
  data2['book_idx'])),
  shape = (num_users, num_books))
sparse_arr

<92106x270151 sparse matrix of type '<class 'numpy.float64'>'
	with 1031136 stored elements in COOrdinate format>

In [32]:
print(sparse_arr.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [33]:
!pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (4.66.2)

In [34]:
from tqdm.notebook import tqdm

In [35]:
U, S, V = linalg.svds(sparse_arr, k = 1550) # 실험끝에 찾은 임계 값

In [ ]:
U.shape, S.shape, V.shape

In [ ]:
U, V, S

In [ ]:
test_user_id = 88705
test_user_df = data2[data2['user_id'] == test_user_id]
test_user_idx = test_user_df['user_idx'].iloc[0]
test_user_idx

83824

In [ ]:
test_user_df

,user_id,ISBN,rating,Location,Age,title,user_idx,book_idx
1021248,88705,0525144609,2.000,"put-in-bay, ohio, usa",NaN,Leviathan,83824,135537

In [ ]:
pred_target_user = U[test_user_idx] @ np.diag(S) @ V

In [ ]:
test_df = data2[data2['user_idx'] == test_user_idx]
for i, sr in enumerate(test_df.itertuples()):
    if i > 20:
        break
    print(f'{sr.rating} -> {pred_target_user[sr.book_idx]:.1f}')

0.0 -> -0.2
0.0 -> 0.1
0.0 -> -0.0
0.0 -> -0.0
10.0 -> 12.6
9.0 -> 9.8
0.0 -> 0.1
9.0 -> 3.5
0.0 -> 0.1
0.0 -> 0.0
0.0 -> 0.5
7.0 -> 8.6
0.0 -> -0.3
0.0 -> 0.0
9.0 -> 11.5
0.0 -> -0.0
8.0 -> 10.7
8.0 -> 10.3
0.0 -> -0.1
0.0 -> 0.0
0.0 -> 0.1

In [ ]:
from sklearn.metrics import mean_squared_error
import math

indices = test_df['book_idx'].to_numpy()
MSE = mean_squared_error(pred_target_user[indices], test_df['rating'].to_list())

RMSE = math.sqrt(MSE)
RMSE

2.905397814840465

In [ ]:
print(pred_target_user.shape)
print(len(pred_target_user))
pred_target_user.tolist()

In [ ]:
book_pred_df = book_df[['ISBN','Book-Title']]
book_pred_df['book_idx'] = book_pred_df['ISBN'].map(book2idx_dict) # isbn의 value들을 index로 변환하여 book_idx col에 저장
book_pred_df = book_pred_df.sort_values('book_idx')
book_pred_df

<ipython-input-99-6ce7d468c5f0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  book_pred_df['book_idx'] = book_pred_df['ISBN'].map(book2idx_dict) # isbn의 value들을 index로 변환하여 book_idx col에 저장

,ISBN,Book-Title,book_idx
2966,034545104X,Flesh Tones: A Novel,0.000
225816,0155061224,Rites of Passage,1.000
11053,0446520802,The Notebook,2.000
246838,052165615X,Help!: Level 1,3.000
246839,0521795028,The Amsterdam Connection : Level 4 (Cambridge ...,4.000
...,...,...,...
271341,1874166633,Introducing Nietzsche (Foundations in Children...,NaN
271342,0130897930,Core Web Programming (2nd Edition),NaN
271343,020130998X,The Unified Modeling Language Reference Manual...,NaN
271344,2268032019,Petite histoire de la d?Â©sinformation,NaN
271347,3442150663,Der Mossad.,NaN

In [ ]:
len(pred_target_user), len(book_pred_df)

(270151, 271360)

In [ ]:
book_pred_df =  book_pred_df[book_pred_df['book_idx'].notna()]
#book_df의 length와 pred_target_user의 length가 다르기 때문에 NaN 값으로 치환되는 index를 제거함으로써 길이를 맞추고 병합

In [ ]:
len(pred_target_user)

270151

In [ ]:
book_merged_df = pd.merge(book_pred_df, test_user_df[['ISBN', 'rating']], on = 'ISBN', how = 'left')
book_merged_df['re_score'] = pred_target_user

In [ ]:
pred_target_user

In [ ]:
pd.options.display.float_format = '{:.3f}'.format #지수 표현 제거

In [ ]:
pd.reset_option('display.float_format') #원래 표현 방식

In [ ]:
book_merged_df.sort_values('rating', ascending = False)[:10]

,ISBN,Book-Title,book_idx,rating,re_score
135537,0525144609,Leviathan,135537.000,2.000,0.000
0,034545104X,Flesh Tones: A Novel,0.000,NaN,0.000
1,0155061224,Rites of Passage,1.000,NaN,0.000
2,0446520802,The Notebook,2.000,NaN,0.000
3,052165615X,Help!: Level 1,3.000,NaN,0.000
4,0521795028,The Amsterdam Connection : Level 4 (Cambridge ...,4.000,NaN,0.000
5,2080674722,Les Particules Elementaires,5.000,NaN,0.000
6,038550120X,A Painted House,6.000,NaN,-0.000
7,0425115801,Lightning,7.000,NaN,0.000
8,0449006522,Manhattan Hunt Club,8.000,NaN,0.000

In [ ]:
book_merged_df[book_merged_df['rating'] == 0].sort_values('re_score', ascending = False)

Empty DataFrame
Columns: [ISBN, Book-Title, book_idx, rating, re_score]
Index: []